sudo: required
language: cpp

env:
  BUILD_DIR=/tmp/build
  SRC_DIR=/tmp/checkout
  COVERALLS_REPO_TOKEN=4MbPQVwHTR2vXt7nn1z1R3aBJUrE4gyCn
  
services:
  - docker

before_install:
  - docker pull ruschi/devlinuxqtquick2:latest
  - docker run -itd --name build_container ruschi/devlinuxqtquick2
  - docker exec build_container python -m pip install cpp-coveralls
  - docker exec build_container git clone https://github.com/truschival/DigitalRoosterGui.git $SRC_DIR

script:
  - docker exec build_container cmake -H$SRC_DIR -B$BUILD_DIR -DBUILD_TESTS=On -DTEST_COVERAGE=On -DBUILD_GTEST_FROM_SRC=On
  - docker exec build_container cmake --build $BUILD_DIR
  - docker exec build_container $BUILD_DIR/bin/DigitalRooster_gtest --gtest_filter=-Player*
  
after_success:
  - docker exec build_container /home/build/.local/bin/coveralls -b $BUILD_DIR -E '.*moc_.*' -E '.*automoc_dir.*' -E '.*/GTestExternal/.*' -E '/usr/.*' 
